### ISSUE TITLE
issue on snort.social desktop browser & Desktop application

### ISSUE THREAD

**Issue by VenetiaSuchdev** [Xeift/Nostr-Bot#2]
HI Can anyone assist me.  I am having trouble with my profile on the snort.social desktop browser and application.  This issue is not occurring on the mobile application in Damus or Amethyst.  If I or anyone tries to view my profile by clicking on my name or profile picture we get an error message.  Which ultimately means that my profile looks less than legitimate.  How can I resolve this issue please?  I have asked on Nostr but have had no response, not sure if  it is because no one can respond or because no one knows!
Please see attached image of the error message. 
![snort error](https://user-images.githubusercontent.com/127320297/223738819-adc0d19e-f4a2-4cf3-8861-f4eb7132a56a.JPG)

**Comment by Xeift** [comment]
snort.social, Damus, Amethyst are different clients, you can take them as browser and take nostr as Internet.
According to your description, I think there's something wrong with snort.social so you should contact the author of snort.social instead of nostr.

**Comment by VenetiaSuchdev** [comment]
Oh I see. How do I find the author of snort.social? Sorry to ask what seems to be a silly question.

**Comment by Xeift** [comment]
https://snort.social/donate
